create table "public"."test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."test" enable row level security;

CREATE UNIQUE INDEX test_pkey1 ON public.test USING btree (id);

alter table "public"."test" add constraint "test_pkey1" PRIMARY KEY using index "test_pkey1";


